set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[0]}]

set_property PULLUP true [get_ports {adc_data[13]}]
set_property PULLUP true [get_ports {adc_data[12]}]
set_property PULLUP true [get_ports {adc_data[11]}]
set_property PULLUP true [get_ports {adc_data[10]}]
set_property PULLUP true [get_ports {adc_data[9]}]
set_property PULLUP true [get_ports {adc_data[8]}]
set_property PULLUP true [get_ports {adc_data[7]}]
set_property PULLUP true [get_ports {adc_data[6]}]
set_property PULLUP true [get_ports {adc_data[5]}]
set_property PULLUP true [get_ports {adc_data[4]}]
set_property PULLUP true [get_ports {adc_data[3]}]
set_property PULLUP true [get_ports {adc_data[2]}]
set_property PULLUP true [get_ports {adc_data[1]}]
set_property PULLUP true [get_ports {adc_data[0]}]


set_property PACKAGE_PIN B11 [get_ports {adc_data[13]}]
set_property PACKAGE_PIN D10 [get_ports {adc_data[12]}]
set_property PACKAGE_PIN D11 [get_ports {adc_data[11]}]
set_property PACKAGE_PIN E10 [get_ports {adc_data[10]}]
set_property PACKAGE_PIN E12 [get_ports {adc_data[9]}]
set_property PACKAGE_PIN H12 [get_ports {adc_data[8]}]
set_property PACKAGE_PIN B10 [get_ports {adc_data[7]}]
set_property PACKAGE_PIN K12 [get_ports {adc_data[6]}]
set_property PACKAGE_PIN F11 [get_ports {adc_data[5]}]
set_property PACKAGE_PIN K13 [get_ports {adc_data[4]}]
set_property PACKAGE_PIN F12 [get_ports {adc_data[3]}]
set_property PACKAGE_PIN J10 [get_ports {adc_data[2]}]
set_property PACKAGE_PIN G10 [get_ports {adc_data[1]}]
set_property PACKAGE_PIN J11 [get_ports {adc_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]

set_property PULLUP true [get_ports {dac_data[13]}]
set_property PULLUP true [get_ports {dac_data[12]}]
set_property PULLUP true [get_ports {dac_data[11]}]
set_property PULLUP true [get_ports {dac_data[10]}]
set_property PULLUP true [get_ports {dac_data[9]}]
set_property PULLUP true [get_ports {dac_data[8]}]
set_property PULLUP true [get_ports {dac_data[7]}]
set_property PULLUP true [get_ports {dac_data[6]}]
set_property PULLUP true [get_ports {dac_data[5]}]
set_property PULLUP true [get_ports {dac_data[4]}]
set_property PULLUP true [get_ports {dac_data[3]}]
set_property PULLUP true [get_ports {dac_data[2]}]
set_property PULLUP true [get_ports {dac_data[1]}]
set_property PULLUP true [get_ports {dac_data[0]}]


set_property PACKAGE_PIN AD12 [get_ports {dac_data[13]}]
set_property PACKAGE_PIN AD10 [get_ports {dac_data[12]}]
set_property PACKAGE_PIN AE10 [get_ports {dac_data[11]}]
set_property PACKAGE_PIN AA11 [get_ports {dac_data[10]}]
set_property PACKAGE_PIN AF10 [get_ports {dac_data[9]}]
set_property PACKAGE_PIN AA10 [get_ports {dac_data[8]}]
set_property PACKAGE_PIN AE12 [get_ports {dac_data[7]}]
set_property PACKAGE_PIN AF11 [get_ports {dac_data[6]}]
set_property PACKAGE_PIN AF12 [get_ports {dac_data[5]}]
set_property PACKAGE_PIN AG11 [get_ports {dac_data[4]}]
set_property PACKAGE_PIN AG10 [get_ports {dac_data[3]}]
set_property PACKAGE_PIN AH12 [get_ports {dac_data[2]}]
set_property PACKAGE_PIN AH10 [get_ports {dac_data[1]}]
set_property PACKAGE_PIN AH11 [get_ports {dac_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk]

set_property PACKAGE_PIN H11 [get_ports adc_clk]
set_property PACKAGE_PIN AC12 [get_ports dac_clk]

set_property DRIVE 16 [get_ports adc_clk]
set_property DRIVE 16 [get_ports dac_clk]
set_property SLEW FAST [get_ports adc_clk]
set_property SLEW FAST [get_ports dac_clk]

# LED0 (DS8) - Pin E8 (HP Bank, using compatible LVCMOS18 standard)
set_property PACKAGE_PIN E8 [get_ports {led_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[0]}]

# LED1 (DS7) - Pin F8 (HP Bank, using compatible LVCMOS18 standard)
set_property PACKAGE_PIN F8 [get_ports {led_1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_1[0]}]
